apiVersion: {{ .Values.rbacApiVersion }}
kind: ClusterRole
metadata:
  name: system:controller:operator-lifecycle-manager
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["watch", "list", "get", "create", "update", "patch", "delete", "deletecollection", "escalate", "bind"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-operator-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: {{ .Values.rbacApiVersion }}
kind: ClusterRoleBinding
metadata:
  name: olm-operator-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: {{ .Values.rbacApiVersion }}
  kind: ClusterRole
  name: system:controller:operator-lifecycle-manager
subjects:
  - kind: ServiceAccount
    name: olm-operator-serviceaccount
    namespace: {{ .Release.Namespace }}